name: Build and Deploy

on:
  push:
    branches:
      - GHactions 

jobs:
  build:
    runs-on: self-hosted

    env:
      REPO_DIR: 'DevOps2024'
      DOCKER_IMAGE: 'ttl.sh/alukan-devops:latest'
      CONTAINER_NAME: 'alukan-devops'
      CONTAINER_PORT: '4444'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: GHactions 

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
          docker push ${{ env.DOCKER_IMAGE }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.105.3
          username: vagrant
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl start docker
            sudo docker ps -a
            sudo docker stop ${{ env.CONTAINER_NAME }} || true
            sudo docker rm ${{ env.CONTAINER_NAME }} || true
            sudo docker pull ${{ env.DOCKER_IMAGE }}
            sudo docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.CONTAINER_PORT }}:${{ env.CONTAINER_PORT }} ${{ env.DOCKER_IMAGE }}


